// Code generated by protoc-gen-go. DO NOT EDIT.

package proto

type MessageType int32

const (
	MessageType_TEXT        MessageType = 0
	MessageType_TASK        MessageType = 1
	MessageType_INVITE      MessageType = 2
	MessageType_RESPONSE   MessageType = 3
	MessageType_FORWARD    MessageType = 4
	MessageType_HEARTBEAT   MessageType = 5
	MessageType_INVOKE_TOOL MessageType = 10
	MessageType_TOOL_RESULT MessageType = 11
	MessageType_ORCHESTRATE MessageType = 12
)

func (x MessageType) String() string {
	switch x {
	case 0:  return "TEXT"
	case 1:  return "TASK"
	case 2:  return "INVITE"
	case 3:  return "RESPONSE"
	case 4:  return "FORWARD"
	case 5:  return "HEARTBEAT"
	case 10: return "INVOKE_TOOL"
	case 11: return "TOOL_RESULT"
	case 12: return "ORCHESTRATE"
	default: return "UNKNOWN"
	}
}

type Capability struct {
	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Params      []string `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
}

func (x *Capability) Reset() {}

type AgentInfo struct {
	Id           string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Capabilities []*Capability `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Port         int32        `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *AgentInfo) Reset() {}

type AgentMessage struct {
	Id            string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64       `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SenderId      string      `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverIds   []string    `protobuf:"bytes,4,rep,name=receiver_ids,json=receiverIds,proto3" json:"receiver_ids,omitempty"`
	Type          MessageType `protobuf:"varint,5,opt,name=type,proto3,enum=agent.MessageType" json:"type,omitempty"`
	Payload       []byte      `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	ShouldForward bool        `protobuf:"varint,7,opt,name=should_forward,json=shouldForward,proto3" json:"should_forward,omitempty"`
	HopCount      uint32      `protobuf:"varint,8,opt,name=hop_count,json=hopCount,proto3" json:"hop_count,omitempty"`
	MaxHops       uint32      `protobuf:"varint,9,opt,name=max_hops,json=maxHops,proto3" json:"max_hops,omitempty"`
	Visited       []string    `protobuf:"bytes,10,rep,name=visited,proto3" json:"visited,omitempty"`
}

func (x *AgentMessage) Reset() {}
