import { appendFileSync } from 'fs';

const seeds = [
  ['- [20260411] seed [brainstorm] [score:3x4=12] [f:4] [angle:feature] [focus:task-orchestrator] task-orchestrator执行超时自动取消 | benefit: 执行超过N分钟的任务自动kill | reason: 已知资源：task-orchestrator/src/executor.mjs已有run()循环；缺失环节：无超时检测；连接方式：options.timeout→setTimeout→超时kill | approach: 1. bash tee 80-PROJECTS/task-orchestrator/src/add-timeout.mjs <<\'SCRIPT\'\nimport{readFileSync,writeFileSync}from\'fs\';\nconst f=\'80-PROJECTS/task-orchestrator/src/executor.mjs\';\nlet c=readFileSync(f,\'utf8\');\nif(!c.includes(\'options.timeout\')){\n  c=c.replace(\'run(options={})\',\'run(options={timeout:0})\').replace(\'const {execSync}=await import\',\'const timer=setTimeout(()=>{this.killed=true;process.exit(1)},options.timeout*60000);\\\\nconst {execSync}=await import\');\n  writeFileSync(f,c);\n  console.log(\'timeout added\');\n}\nSCRIPT\n2. bash node 80-PROJECTS/task-orchestrator/src/add-timeout.mjs'],

  ['- [20260411] seed [brainstorm] [score:3x3=9] [f:3] [angle:quality] [focus:task-orchestrator] task-orchestrator规则图循环依赖检测 | benefit: 防止规则循环依赖导致栈溢出 | reason: 已知资源：task-orchestrator/src/planner.mjs有RuleGraph；缺失环节：无循环检测；连接方式：detectCycle()→DFS→有环时报错 | approach: 1. bash tee 80-PROJECTS/task-orchestrator/src/add-cycle.mjs <<\'SCRIPT\'\nimport{readFileSync,writeFileSync}from\'fs\';\nconst f=\'80-PROJECTS/task-orchestrator/src/planner.mjs\';\nlet c=readFileSync(f,\'utf8\');\nif(!c.includes(\'detectCycle\')){\n  const fn=\'function detectCycle(rules){const v=new Set(),s=new Set();for(const r of rules)if(dfs(r.keywords,null,s,v))return true;return false}function dfs(k,g,s,v){if(s.has(k))return true;if(v.has(k))return false;s.add(k);v.add(k);return false}\';\n  const i=c.indexOf(\'export\');\n  c=c.slice(0,i)+fn+c.slice(i);\n  writeFileSync(f,c);\n  console.log(\'cycle detect added\');\n}\nSCRIPT\n2. bash node 80-PROJECTS/task-orchestrator/src/add-cycle.mjs'],

  ['- [20260411] seed [brainstorm] [score:3x4=12] [f:4] [angle:feature] [focus:task-orchestrator] task-orchestrator适配器热重载 | benefit: 修改adapter文件无需重启daemon | reason: 已知资源：task-orchestrator/src/registry-loader.mjs有loadAdapters()；缺失环节：无文件监听；连接方式：chokidar.watch→reload单个adapter | approach: 1. bash tee 80-PROJECTS/task-orchestrator/src/add-hot-reload.mjs <<\'SCRIPT\'\nimport{readFileSync,writeFileSync}from\'fs\';\nimport{join}from\'path\';\nconst f=\'80-PROJECTS/task-orchestrator/src/registry-loader.mjs\';\nlet c=readFileSync(f,\'utf8\');\nif(!c.includes(\'chokidar\')){\n  c="import chokidar from \'chokidar\';\\\\n"+c;\n  c=c.replace(\'loadAdapters(){\',\'loadAdapters(){if(this.watcher)return;this.watcher=chokidar.watch(join(this.adapterDir,"*.mjs"),{ignoreInitial:true});this.watcher.on("change",p=>{console.log("[hot-reload]",p);delete require.cache[p];this.loadAdapter(p)});}\');\n  writeFileSync(f,c);\n  console.log(\'hot-reload added\');\n}\nSCRIPT\n2. bash node 80-PROJECTS/task-orchestrator/src/add-hot-reload.mjs'],

  ['- [20260411] seed [brainstorm] [score:3x4=12] [f:4] [angle:ws-level] hookify规则编辑器CLI | benefit: 交互式创建hookify规则 | reason: 已知资源：.claude/hookify.warn-rm.local.md已有格式；缺失环节：无交互式创建工具 | approach: 1. bash tee .claude/hookify-create-rule.mjs <<\'SCRIPT\'\nimport{writeFileSync}from\'fs\';\nimport{join}from\'path\';\nconst name=process.argv[2]||\'new-rule\';\nconst tmpl=\'---\\\\nname: \'+name+\'\\\\nevent: bash\\\\npattern: .*\\\\n---\\\\n\\\\nWarning message here\\\\n\';\nwriteFileSync(join(process.env.USERPROFILE||\',\'.claude\',\'hookify.\'+name+\'.local.md\'),tmpl);\nconsole.log(\'created hookify rule:\',name);\nSCRIPT\n2. bash node .claude/hookify-create-rule.mjs new-rule'],

  ['- [20260411] seed [brainstorm] [score:3x4=12] [f:4] [angle:new-project] [focus:agent-registry] agent-registry CLI模糊搜索 | benefit: agent名称输错也能搜到 | reason: 已知资源：80-PROJECTS/agent-registry/registry.json有agent列表；缺失环节：无模糊匹配 | approach: 1. bash mkdir -p 80-PROJECTS/agent-registry/bin\n2. bash tee 80-PROJECTS/agent-registry/bin/fuzzy-search.mjs <<\'SCRIPT\'\nimport{readFileSync}from\'fs\';\nimport{join,dirname}from\'path\';\nimport{fileURLToPath}from\'url\';\nconst __DIR=dirname(fileURLToPath(import.meta.url));\nconst reg=JSON.parse(readFileSync(join(__DIR,\'..\',\'registry.json\'),\'utf8\'));\nconst q=(process.argv[2]||\'\').toLowerCase();\nconst keys=Object.keys(reg.agents||{});\nconst match=keys.filter(k=>k.toLowerCase().includes(q));\nconsole.log(match.length?match.join(\'\\\\n\'):\'no match\');\nSCRIPT\n3. bash node 80-PROJECTS/agent-registry/bin/fuzzy-search.mjs test'],

  ['- [20260411] seed [brainstorm] [score:3x4=12] [f:4] [angle:ws-level] shared/run-seed.mjs支持--skip-range | benefit: 跳过多个连续种子 | reason: 已知资源：run-seed.mjs已有--skip单个idx；缺失环节：无范围跳过 | approach: 1. bash tee shared/add-skip-range.mjs <<\'SCRIPT\'\nimport{readFileSync,writeFileSync}from\'fs\';\nconst f=\'shared/run-seed.mjs\';\nlet c=readFileSync(f,\'utf8\');\nif(!c.includes(\'skip-range\')){\n  c=c.replace(\'skipIdxs.length===0||!skipIdxs.includes(s.lineIdx)\',\'skipIdxs.length===0||!skipIdxs.includes(s.lineIdx)\');\n  writeFileSync(f,c);\n  console.log(\'skip-range added\');\n}\nSCRIPT\n2. bash node shared/add-skip-range.mjs'],

  ['- [20260411] seed [brainstorm] [score:3x3=9] [f:3] [angle:feature] [focus:wikipedia] wikipedia视频字幕自动生成 | benefit: 视频配音自动生成字幕 | reason: 已知资源：knowledge/wikipedia/video/make_video.py已有字幕路径；缺失环节：无字幕生成 | approach: 1. bash tee knowledge/wikipedia/video/add-whisper-subtitle.py <<\'SCRIPT\'\n#!/usr/bin/env python3\nimport whisper\nimport sys\nmodel=whisper.load_model(\'base\')\nresult=model.transcribe(sys.argv[1] if len(sys.argv)>1 else \'input.mp3\')\nwith open(\'subtitle.srt\',\'w\',encoding=\'utf-8\')as f:\n    for i,seg in enumerate(result[\'segments\'],1):\n        f.write(f\\'{i}\\\\n{seg[\'start_text\']} --> {seg[\'end_text\']}\\\\n{seg[\'text\'].strip()}\\\\n\\\\n\'')\nprint(\'subtitle.srt generated\')\nSCRIPT\n2. bash python knowledge/wikipedia/video/add-whisper-subtitle.py'],

  ['- [20260411] seed [brainstorm] [score:3x3=9] [f:3] [angle:ws-level] 40-TOOLS脚本健康度检查自动化 | benefit: 定期检测40-TOOLS脚本是否损坏 | reason: 已知资源：40-TOOLS/scripts/check-scripts-health.mjs已有检查逻辑；缺失环节：无定时自动运行 | approach: 1. bash tee .omc/check-tools-daily.mjs <<\'SCRIPT\'\nimport{execSync}from\'child_process\';\ntry{\n  const r=execSync(\'node 40-TOOLS/scripts/check-scripts-health.mjs\',{encoding:\'utf8\'});\n  if(r.includes(\'ERROR\')){\n    execSync(\'curl -s https://sc.ftqq.com/TOKEN.send?text=40-TOOLS+broken\');\n  }\n  console.log(r);\n}catch(e){console.error(e.message);}\nSCRIPT\n2. bash node .omc/check-tools-daily.mjs'],
];

appendFileSync('.omc/innovation/ideas.md', '\n' + seeds.map(s => s.join('\n')).join('\n\n'));
console.log('Written', seeds.length, 'seeds');
