#!/usr/bin/env pwsh
# Analyze Markdown link heat (citation count)
# Usage: .\analyze-link-heat.ps1 [-Path <dir>]

param(
    [string]$Path = "D:\OpenClaw\workspace",
    [string]$OutputFile = "link-heat-report.md"
)

Write-Host "Analyzing link heat..." -ForegroundColor Cyan
Write-Host "Path: $Path"
Write-Host ""

$heatMap = @{}
$mdFiles = Get-ChildItem -Path $Path -Filter "*.md" -Recurse -Exclude $OutputFile,"broken-links-report.md"

$linkPattern = '\[\[([^\]|]+)(?:\|[^\]]+)?\]\]'

foreach ($file in $mdFiles) {
    $content = Get-Content $file.FullName -Raw -ErrorAction SilentlyContinue
    if (-not $content) { continue }
    
    $links = [regex]::Matches($content, $linkPattern)
    
    foreach ($link in $links) {
        $linkText = $link.Groups[1].Value.Trim()
        
        # Skip external links
        if ($linkText -match '^(http|https|mailto:)') { continue }
        
        # Normalize link path
        $normalizedLink = $linkText -replace '/README$','' -replace '\.md$',''
        
        if ($heatMap.ContainsKey($normalizedLink)) {
            $heatMap[$normalizedLink]++
        } else {
            $heatMap[$normalizedLink] = 1
        }
    }
}

# Sort and output
$sorted = $heatMap.GetEnumerator() | Sort-Object Value -Descending

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Link Heat TOP 20" -ForegroundColor Cyan
Write-Host "========================================"

$top20 = $sorted | Select-Object -First 20
$maxHeat = if ($top20) { $top20[0].Value } else { 0 }

foreach ($item in $top20) {
    $barLength = [math]::Round(($item.Value / $maxHeat) * 20)
    $bar = "#" * $barLength
    $heatPercent = [math]::Round($item.Value / $sorted.Count * 100, 1)
    
    Write-Host "  $($item.Key)" -NoNewline
    Write-Host " $bar $($item.Value) times ($heatPercent%)" -ForegroundColor Green
}

Write-Host ""
Write-Host "Total unique links: $($heatMap.Count)"
$totalRefs = $heatMap.Values | Measure-Object -Sum
Write-Host "Total references: $($totalRefs.Sum)"
Write-Host ""

# Generate report
$report = @"
# Link Heat Analysis Report

**Generated:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')  
**Path:** $Path  
**Unique links:** $($heatMap.Count)  
**Total references:** $($totalRefs.Sum)

---

## TOP 20 Hot Links

| Rank | Link | Citations | Heat |
|------|------|-----------|------|
"@

$rank = 1
foreach ($item in $sorted | Select-Object -First 20) {
    $heatPercent = [math]::Round($item.Value / $sorted.Count * 100, 1)
    $report += "| $rank | ``$($item.Key)`` | $($item.Value) | $heatPercent% |`n"
    $rank++
}

$report += @"

---

## Heat Distribution

| Heat Range | Links | Percent |
|------------|-------|---------|
"@

$ranges = @(
    @{Name = "Super Hot (10+)"; Min = 10; Max = 999},
    @{Name = "Hot (5-9)"; Min = 5; Max = 9},
    @{Name = "Normal (2-4)"; Min = 2; Max = 4},
    @{Name = "Cold (1)"; Min = 1; Max = 1}
)

foreach ($range in $ranges) {
    $count = ($heatMap.Values | Where-Object { $_ -ge $range.Min -and $_ -le $range.Max }).Count
    $percent = [math]::Round($count / $heatMap.Count * 100, 1)
    $report += "| $($range.Name) | $count | $percent% |`n"
}

$report += @"

---

## Insights

**High-frequency linked docs should:**
1. Be placed in accessible locations
2. Keep content up-to-date
3. Add detailed descriptions
4. Consider creating mirrors/shortcuts

**Cold docs may need:**
1. Re-evaluate value
2. Improve discoverability
3. Consider archiving or deleting

---

*Auto-generated by analyze-link-heat.ps1*
"@

$reportPath = Join-Path $Path $OutputFile
$report | Out-File -FilePath $reportPath -Encoding utf8
Write-Host "Report saved: $reportPath" -ForegroundColor Green
Write-Host ""
Write-Host "Done!" -ForegroundColor Cyan
