#!/usr/bin/env pwsh
# Broken Link Fix Suggestions - 断链自动修复建议
# 用法：.\broken-link-fixer.ps1 [-Path <dir>] [-ReportFile <file>]

param(
    [string]$Path = "D:\OpenClaw\workspace",
    [string]$ReportFile = "broken-links-report.md",
    [string]$OutputFile = "broken-link-fixes.md"
)

Write-Host "Broken Link Fix Suggestions - 断链修复建议" -ForegroundColor Cyan
Write-Host ""

$reportPath = Join-Path $Path $ReportFile

if (-not (Test-Path $reportPath)) {
    Write-Host "Error: Broken links report not found" -ForegroundColor Red
    Write-Host "Run check-broken-links.ps1 first" -ForegroundColor Yellow
    exit 1
}

Write-Host "Step 1: Analyzing broken links..." -ForegroundColor Yellow

$report = Get-Content $reportPath -Raw
$brokenLinks = @()

# Parse report (simple parsing)
$lines = $report -split "`n"
foreach ($line in $lines) {
    if ($line -match '\| ([^\|]+) \| ``([^\`]+)`` \|') {
        $file = $matches[1].Trim()
        $link = $matches[2].Trim()
        
        # Skip template placeholders
        if ($link -match '^(xxx|论文 | 概念 | 趋势 | 笔记|OK|)$') { continue }
        if ($link -match '^\d+\.\d+') { continue }  # Skip numbers like "10.0, 50.0"
        
        $brokenLinks += @{
            File = $file
            Link = $link
        }
    }
}

Write-Host "Found $($brokenLinks.Count) real broken links" -ForegroundColor Cyan
Write-Host ""

Write-Host "Step 2: Generating fix suggestions..." -ForegroundColor Yellow

$suggestions = @{}

foreach ($broken in $brokenLinks) {
    $link = $broken.Link
    
    # Try to find similar files
    $possibleMatches = @()
    
    # Search by name
    $searchResults = Get-ChildItem -Path $Path -Filter "*$link*.md" -Recurse -ErrorAction SilentlyContinue |
        Select-Object -First 5 -ExpandProperty FullName
    
    foreach ($match in $searchResults) {
        $relPath = $match.Replace($Path, "").TrimStart('\') -replace '.md$',''
        $possibleMatches += $relPath
    }
    
    # Search by keywords (split link by common separators)
    $keywords = $link -split '[\\/_-]' | Where-Object { $_.Length -gt 3 }
    foreach ($kw in $keywords) {
        $kwResults = Get-ChildItem -Path $Path -Filter "*$kw*.md" -Recurse -ErrorAction SilentlyContinue |
            Select-Object -First 3 -ExpandProperty FullName
        
        foreach ($match in $kwResults) {
            $relPath = $match.Replace($Path, "").TrimStart('\') -replace '.md$',''
            if ($possibleMatches -notcontains $relPath) {
                $possibleMatches += $relPath
            }
        }
    }
    
    if ($possibleMatches.Count -gt 0) {
        $suggestions[$broken.File + "|" + $broken.Link] = $possibleMatches | Select-Object -Unique
    }
}

Write-Host "Generated suggestions for $($suggestions.Count) broken links" -ForegroundColor Cyan
Write-Host ""

Write-Host "Step 3: Creating fix report..." -ForegroundColor Yellow

$fixReport = @"
# Broken Link Fix Suggestions

**Generated:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')  
**Total broken links:** $($brokenLinks.Count)  
**With suggestions:** $($suggestions.Count)  
**Without suggestions:** $($brokenLinks.Count - $suggestions.Count)

---

## 🔧 Links with Fix Suggestions

"@

foreach ($key in $suggestions.Keys) {
    $file, $link = $key -split '\|', 2
    $matches = $suggestions[$key]
    
    $fixReport += "### ``$link`` in ``$file```n`n"
    $fixReport += "**Suggested replacements:**`n`n"
    
    $i = 1
    foreach ($match in $matches | Select-Object -First 5) {
        $fixReport += "$i. [[$match]]`n"
        $i++
    }
    
    $fixReport += "`n"
}

$fixReport += @"

---

## ❌ Links without Suggestions

These links need manual review:

"@

$noSuggestionCount = 0
foreach ($broken in $brokenLinks) {
    $key = $broken.File + "|" + $broken.Link
    if (-not $suggestions.ContainsKey($key)) {
        $fixReport += "- ``$($broken.Link)`` in ``$($broken.File)```n"
        $noSuggestionCount++
        
        if ($noSuggestionCount -ge 50) {
            $fixReport += "- ... and $($brokenLinks.Count - $suggestions.Count - 50) more`n"
            break
        }
    }
}

$fixReport += @"

---

## 📋 Action Items

1. **Review suggestions** - Check if suggested links are appropriate
2. **Apply fixes** - Replace broken links with correct ones
3. **Manual review** - Handle links without suggestions
4. **Re-run check** - Run check-broken-links.ps1 to verify fixes

---

*Auto-generated by broken-link-fixer.ps1*
"@

$fixReport | Out-File -FilePath (Join-Path $Path $OutputFile) -Encoding utf8

Write-Host "Fix report saved: $OutputFile" -ForegroundColor Green
Write-Host ""
Write-Host "Done!" -ForegroundColor Cyan
