#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Test Framework Enhancer - Automated Testing System
Features: Auto test generation, coverage analysis, performance benchmarking, CI/CD integration

Usage:
    python test_enhancer.py --generate
    python test_enhancer.py --run
    python test_enhancer.py --coverage
    python test_enhancer.py --benchmark
"""

import os
import sys
import json
import time
import unittest
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional, Callable
from dataclasses import dataclass, asdict
import io
from contextlib import redirect_stdout

# Optional imports
try:
    import coverage
    COVERAGE_AVAILABLE = True
except ImportError:
    COVERAGE_AVAILABLE = False

try:
    import cProfile
    import pstats
    PROFILE_AVAILABLE = True
except ImportError:
    PROFILE_AVAILABLE = False

# Workspace root
WORKSPACE = Path(__file__).parent.parent

# Ensure UTF-8 for Windows
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding='utf-8')


@dataclass
class TestResult:
    """Test execution result"""
    test_name: str
    status: str  # pass/fail/skip/error
    duration: float
    message: str
    timestamp: str


@dataclass
class CoverageResult:
    """Coverage analysis result"""
    file: str
    total_lines: int
    covered_lines: int
    coverage_percent: float
    missing_lines: List[int]


@dataclass
class BenchmarkResult:
    """Performance benchmark result"""
    function: str
    calls: int
    total_time: float
    avg_time: float
    min_time: float
    max_time: float
    memory_usage: float


class TestFrameworkEnhancer:
    """Automated testing system"""
    
    def __init__(self):
        self.test_dir = WORKSPACE / "30-scripts-tools" / "tests"
        self.test_dir.mkdir(parents=True, exist_ok=True)
        
        self.results_dir = WORKSPACE / "20-data-reports" / "test-results"
        self.results_dir.mkdir(parents=True, exist_ok=True)
        
        self.results_file = self.results_dir / "test_results.json"
        self.coverage_file = self.results_dir / "coverage_results.json"
        self.benchmark_file = self.results_dir / "benchmark_results.json"
        
        self.results = []
        self.coverage_results = []
        self.benchmark_results = []
        
        self.load_state()
    
    def load_state(self):
        """Load test state"""
        if self.results_file.exists():
            with open(self.results_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
                self.results = data.get('results', [])
        
        if self.coverage_file.exists():
            with open(self.coverage_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
                self.coverage_results = data.get('results', [])
        
        if self.benchmark_file.exists():
            with open(self.benchmark_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
                self.benchmark_results = data.get('results', [])
    
    def save_state(self):
        """Save test state"""
        with open(self.results_file, 'w', encoding='utf-8') as f:
            json.dump({
                'results': self.results[-100:],
                'last_updated': datetime.now().isoformat()
            }, f, indent=2, ensure_ascii=False)
        
        with open(self.coverage_file, 'w', encoding='utf-8') as f:
            json.dump({
                'results': self.coverage_results,
                'last_updated': datetime.now().isoformat()
            }, f, indent=2, ensure_ascii=False)
        
        with open(self.benchmark_file, 'w', encoding='utf-8') as f:
            json.dump({
                'results': self.benchmark_results,
                'last_updated': datetime.now().isoformat()
            }, f, indent=2, ensure_ascii=False)
    
    def generate_tests(self, target_dir: Path = None) -> int:
        """Generate test files for existing tools"""
        print("\n" + "="*60)
        print(" Generating Tests")
        print("="*60 + "\n")
        
        if target_dir is None:
            target_dir = WORKSPACE / "30-scripts-tools"
        
        tests_generated = 0
        
        # Find Python files without tests
        for py_file in target_dir.glob("*.py"):
            if py_file.name.startswith('test_') or py_file.name.startswith('_'):
                continue
            
            test_file = self.test_dir / f"test_{py_file.name}"
            
            if test_file.exists():
                print(f"  ⏭️  {test_file.name} (exists)")
                continue
            
            # Generate test file
            module_name = py_file.stem
            
            test_content = f'''#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Tests for {module_name}
Auto-generated by Test Framework Enhancer
"""

import unittest
import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

# Import module to test
try:
    from {module_name} import *
except ImportError:
    pass  # Module may not be importable


class Test{module_name.title().replace("_", "")}(unittest.TestCase):
    """Test cases for {module_name}"""
    
    def setUp(self):
        """Set up test fixtures"""
        pass
    
    def tearDown(self):
        """Tear down test fixtures"""
        pass
    
    def test_import(self):
        """Test module import"""
        # Verify module can be imported
        try:
            import {module_name}
            self.assertTrue(True)
        except ImportError as e:
            self.fail(f"Failed to import {{module_name}}: {{e}}")
    
    def test_main_function(self):
        """Test main function exists"""
        # Check if main function exists
        import {module_name}
        self.assertTrue(hasattr({module_name}, 'main'))
    
    def test_example(self):
        """Example test case"""
        # Replace with actual tests
        self.assertTrue(True)


if __name__ == '__main__':
    unittest.main()
'''
            
            with open(test_file, 'w', encoding='utf-8') as f:
                f.write(test_content)
            
            tests_generated += 1
            print(f"  ✅ {test_file.name}")
        
        print(f"\n✅ Generated {tests_generated} test files\n")
        
        return tests_generated
    
    def run_tests(self, test_pattern: str = "test_*.py") -> Dict:
        """Run all tests"""
        print("\n" + "="*60)
        print(" Running Tests")
        print("="*60 + "\n")
        
        # Discover tests
        loader = unittest.TestLoader()
        suite = unittest.TestSuite()
        
        test_files = list(self.test_dir.glob(test_pattern))
        
        if not test_files:
            print("⚠️  No test files found")
            return {'tests': 0, 'passed': 0, 'failed': 0, 'errors': 0}
        
        print(f"Found {len(test_files)} test files\n")
        
        # Load tests
        for test_file in test_files:
            try:
                module_name = f"tests.{test_file.stem}"
                spec = __import__(module_name, fromlist=[''])
                tests = loader.loadTestsFromModule(spec)
                suite.addTests(tests)
            except Exception as e:
                print(f"  ⚠️  Failed to load {test_file.name}: {e}")
        
        # Run tests
        runner = unittest.TextTestRunner(verbosity=2)
        
        # Capture output
        output = io.StringIO()
        with redirect_stdout(output):
            result = runner.run(suite)
        
        # Process results
        tests_run = result.testsRun
        failures = len(result.failures)
        errors = len(result.errors)
        skipped = len(result.skipped)
        passed = tests_run - failures - errors - skipped
        
        success_rate = (passed / tests_run * 100) if tests_run > 0 else 0
        
        print(f"\n{'='*60}")
        print(" Test Results")
        print(f"{'='*60}")
        print(f"  Total: {tests_run}")
        print(f"  Passed: {passed}")
        print(f"  Failed: {failures}")
        print(f"  Errors: {errors}")
        print(f"  Skipped: {skipped}")
        print(f"  Success Rate: {success_rate:.1f}%")
        print(f"{'='*60}\n")
        
        # Record results
        test_result = {
            'timestamp': datetime.now().isoformat(),
            'total': tests_run,
            'passed': passed,
            'failed': failures,
            'errors': errors,
            'skipped': skipped,
            'success_rate': round(success_rate, 1)
        }
        
        self.results.append(test_result)
        self.save_state()
        
        return test_result
    
    def analyze_coverage(self, target_dir: Path = None) -> List[CoverageResult]:
        """Analyze code coverage"""
        print("\n" + "="*60)
        print(" Analyzing Coverage")
        print("="*60 + "\n")
        
        if not COVERAGE_AVAILABLE:
            print("⚠️  Coverage module not available")
            print("Install: pip install coverage\n")
            return []
        
        if target_dir is None:
            target_dir = WORKSPACE / "30-scripts-tools"
        
        # Run coverage
        cov = coverage.Coverage()
        cov.start()
        
        # Import modules
        for py_file in target_dir.glob("*.py"):
            if py_file.name.startswith('test_') or py_file.name.startswith('_'):
                continue
            
            try:
                module_name = py_file.stem
                spec = __import__(module_name)
            except:
                pass
        
        cov.stop()
        
        # Analyze
        results = []
        
        for py_file in target_dir.glob("*.py"):
            if py_file.name.startswith('test_') or py_file.name.startswith('_'):
                continue
            
            try:
                analysis = cov.analysis(str(py_file))
                total = len(analysis[0])
                executed = len(analysis[1])
                missing = analysis[2]
                
                coverage_pct = (executed / total * 100) if total > 0 else 0
                
                result = CoverageResult(
                    file=str(py_file.relative_to(WORKSPACE)),
                    total_lines=total,
                    covered_lines=executed,
                    coverage_percent=round(coverage_pct, 1),
                    missing_lines=[int(m) for m in missing[:20]]  # First 20 missing
                )
                
                results.append(result)
                
                icon = "✅" if coverage_pct >= 80 else "⚠️" if coverage_pct >= 50 else "❌"
                print(f"  {icon} {py_file.name}: {coverage_pct:.1f}%")
            
            except Exception as e:
                pass
        
        self.coverage_results = [asdict(r) for r in results]
        self.save_state()
        
        # Summary
        avg_coverage = sum(r.coverage_percent for r in results) / len(results) if results else 0
        
        print(f"\n{'='*60}")
        print(" Coverage Summary")
        print(f"{'='*60}")
        print(f"  Files analyzed: {len(results)}")
        print(f"  Average coverage: {avg_coverage:.1f}%")
        print(f"  Files ≥80%: {sum(1 for r in results if r.coverage_percent >= 80)}")
        print(f"  Files <50%: {sum(1 for r in results if r.coverage_percent < 50)}")
        print(f"{'='*60}\n")
        
        return results
    
    def run_benchmark(self, function: Callable, iterations: int = 100) -> BenchmarkResult:
        """Run performance benchmark"""
        print(f"\n📊 Benchmarking {function.__name__}...")
        
        times = []
        
        # Warm up
        for _ in range(10):
            function()
        
        # Measure
        profiler = cProfile.Profile()
        profiler.enable()
        
        for i in range(iterations):
            start = time.perf_counter()
            function()
            end = time.perf_counter()
            times.append(end - start)
        
        profiler.disable()
        
        # Calculate stats
        total_time = sum(times)
        avg_time = total_time / len(times)
        min_time = min(times)
        max_time = max(times)
        
        # Memory (approximate)
        stats = pstats.Stats(profiler)
        memory_usage = stats.total_tt * 1024 * 1024  # Rough estimate
        
        result = BenchmarkResult(
            function=function.__name__,
            calls=iterations,
            total_time=round(total_time, 3),
            avg_time=round(avg_time * 1000, 3),  # ms
            min_time=round(min_time * 1000, 3),  # ms
            max_time=round(max_time * 1000, 3),  # ms
            memory_usage=round(memory_usage, 2)
        )
        
        self.benchmark_results.append(asdict(result))
        self.save_state()
        
        print(f"  Calls: {iterations}")
        print(f"  Total: {total_time:.3f}s")
        print(f"  Average: {avg_time * 1000:.3f}ms")
        print(f"  Min: {min_time * 1000:.3f}ms")
        print(f"  Max: {max_time * 1000:.3f}ms")
        
        return result
    
    def generate_report(self) -> str:
        """Generate test report"""
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        report_file = self.results_dir / f"test_report_{timestamp}.md"
        
        # Get latest results
        latest_result = self.results[-1] if self.results else None
        avg_coverage = sum(r['coverage_percent'] for r in self.coverage_results) / len(self.coverage_results) if self.coverage_results else 0
        
        report = f"""# Test Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Summary

- **Tests Run:** {latest_result['total'] if latest_result else 0}
- **Pass Rate:** {latest_result['success_rate'] if latest_result else 0}%
- **Coverage:** {avg_coverage:.1f}%
- **Benchmarks:** {len(self.benchmark_results)}

## Recent Results

"""
        
        for result in self.results[-10:][::-1]:
            icon = "✅" if result['success_rate'] >= 90 else "⚠️" if result['success_rate'] >= 70 else "❌"
            report += f"- {icon} {result['timestamp'][:19]}: {result['passed']}/{result['total']} ({result['success_rate']}%)\n"
        
        report += f"""
## Coverage by File

| File | Coverage | Status |
|------|----------|--------|
"""
        
        for cov in self.coverage_results[:20]:
            status = "✅" if cov['coverage_percent'] >= 80 else "⚠️" if cov['coverage_percent'] >= 50 else "❌"
            report += f"| {Path(cov['file']).name} | {cov['coverage_percent']}% | {status} |\n"
        
        report += f"""
## Benchmarks

| Function | Avg Time | Calls | Total |
|----------|----------|-------|-------|
"""
        
        for bench in self.benchmark_results[-10:]:
            report += f"| {bench['function']} | {bench['avg_time']}ms | {bench['calls']} | {bench['total_time']}s |\n"
        
        report += f"""
---

*Report generated by Test Framework Enhancer v1.0*
"""
        
        with open(report_file, 'w', encoding='utf-8') as f:
            f.write(report)
        
        print(f"\n✅ Report saved: {report_file}")
        
        return report
    
    def get_statistics(self) -> Dict:
        """Get test statistics"""
        return {
            'total_runs': len(self.results),
            'latest': self.results[-1] if self.results else None,
            'coverage_files': len(self.coverage_results),
            'avg_coverage': sum(r['coverage_percent'] for r in self.coverage_results) / len(self.coverage_results) if self.coverage_results else 0,
            'benchmarks': len(self.benchmark_results)
        }


def main():
    import argparse
    
    parser = argparse.ArgumentParser(description='Test Framework Enhancer')
    parser.add_argument('--generate', action='store_true', help='Generate tests')
    parser.add_argument('--run', action='store_true', help='Run tests')
    parser.add_argument('--coverage', action='store_true', help='Analyze coverage')
    parser.add_argument('--benchmark', action='store_true', help='Run benchmarks')
    parser.add_argument('--report', action='store_true', help='Generate report')
    parser.add_argument('--stats', action='store_true', help='Show statistics')
    args = parser.parse_args()
    
    enhancer = TestFrameworkEnhancer()
    
    if args.generate:
        enhancer.generate_tests()
    
    elif args.run:
        enhancer.run_tests()
    
    elif args.coverage:
        enhancer.analyze_coverage()
    
    elif args.benchmark:
        # Example benchmark
        def example_func():
            sum(range(1000))
        
        enhancer.run_benchmark(example_func)
    
    elif args.report:
        enhancer.generate_report()
    
    elif args.stats:
        stats = enhancer.get_statistics()
        print(json.dumps(stats, indent=2))
    
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
