#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
AUTO-EVOLVE-001 Self-Evolution System
Analyzes patterns, generates improvements, self-programs new capabilities
"""
import json, re, sys, hashlib
from pathlib import Path
from datetime import datetime
from collections import defaultdict, Counter

TOOLS_DIR = Path("30-scripts-tools")
EVOLUTION_DIR = Path("13-memory/.evolution")
EVOLUTION_DIR.mkdir(exist_ok=True)

class SelfEvolution:
    def __init__(self):
        self.evolution_log = EVOLUTION_DIR / "log.json"
        self.load_log()
    
    def load_log(self):
        if self.evolution_log.exists():
            self.log = json.loads(self.evolution_log.read_text(encoding="utf-8", errors="replace"))
        else:
            self.log = {"generations": [], "improvements": [], "created_tools": []}
    
    def save_log(self):
        self.evolution_log.write_text(json.dumps(self.log, indent=2, ensure_ascii=False))
    
    def analyze_patterns(self):
        """Analyze code patterns to find improvement opportunities"""
        patterns = {
            "repeated_code": [],
            "missing_features": [],
            "optimization_points": [],
            "unused_functions": [],
        }
        
        # Analyze tools
        for f in TOOLS_DIR.glob("*_001.py"):
            if f.name.startswith("__"):
                continue
            try:
                content = f.read_text(encoding="utf-8", errors="replace")
                
                # Find repeated patterns
                lines = [l.strip() for l in content.split("\n") if l.strip()]
                
                # Check for TODO/FIXME
                if "TODO" in content or "FIXME" in content:
                    patterns["missing_features"].append(f.name)
                
                # Check for long functions
                if len(content.split("\n")) > 300:
                    patterns["optimization_points"].append(f.name)
                
                # Check for print without logging
                if "print(" in content and "logging" not in content:
                    patterns["optimization_points"].append(f.name)
                    
            except (IOError, OSError):
                pass
        
        return patterns
    
    def generate_improvement(self, tool_name, improvement_type):
        """Generate code improvement for a tool"""
        
        improvements = {
            "add_logging": '''
    # Auto-evolution: Added structured logging
    import logging
    logger = logging.getLogger(__name__)
    logger.setLevel(logging.INFO)
    if not logger.handlers:
        handler = logging.FileHandler("{log_file}")
        handler.setFormatter(logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s"))
        logger.addHandler(handler)
'''.format(log_file=str(EVOLUTION_DIR / f"{tool_name}.log")),
            
            "add_error_handling": '''
    # Auto-evolution: Enhanced error handling
    def safe_execute(func):
        def wrapper(*args, **kwargs):
            try:
                return func(*args, **kwargs)
            except Exception as e:
                logger.error(f"Error in {func.__name__}: {{e}}")
                return None
        return wrapper
''',
            
            "add_caching": '''
    # Auto-evolution: Added caching
    from functools import lru_cache
    @lru_cache(maxsize=128)
    def cached_operation(data):
        # Cached version
        return data
''',
        }
        
        return improvements.get(improvement_type, "")
    
    def create_new_tool(self, spec):
        """Auto-generate a new tool from specification"""
        name = spec.get("name", "new_tool")
        purpose = spec.get("purpose", "Auto-generated tool")
        code = f'''#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
{name.upper()}
Generated by AUTO-EVOLVE-001 on {datetime.now().isoformat()}
Purpose: {purpose}
"""

import json, sys
from pathlib import Path

def main():
    print("[{name}] Auto-generated tool")
    # TODO: Implement functionality

if __name__ == "__main__":
    main()
'''
        
        tool_path = TOOLS_DIR / f"{name}_001.py"
        tool_path.write_text(code, encoding="utf-8")
        
        self.log["created_tools"].append({
            "name": name,
            "purpose": purpose,
            "created": datetime.now().isoformat()
        })
        
        return tool_path
    
    def evolve(self, iterations=3):
        """Run evolution cycles"""
        print(f"\n[AUTO-EVOLVE-001] Starting evolution ({iterations} cycles)")
        print("=" * 50)
        
        results = []
        
        for i in range(iterations):
            print(f"\n[Generation {i+1}]")
            
            # Analyze
            patterns = self.analyze_patterns()
            print(f"  Patterns found: {sum(len(v) for v in patterns.values())}")
            
            # Generate improvements
            improvements = []
            if patterns["optimization_points"]:
                improvements.append("Add caching")
            if patterns["missing_features"]:
                improvements.append("Add error handling")
            
            # Create new tools
            new_tools = []
            if i == 0:  # First generation creates new tools
                # Generate a tool maker
                tool_spec = {
                    "name": f"evolved_tool_{i+1}",
                    "purpose": f"Auto-evolved capability from generation {i+1}"
                }
                path = self.create_new_tool(tool_spec)
                new_tools.append(path.name)
            
            result = {
                "generation": i + 1,
                "patterns": {k: len(v) for k, v in patterns.items()},
                "improvements": improvements,
                "new_tools": new_tools,
            }
            results.append(result)
            
            print(f"  Improvements: {improvements}")
            print(f"  New tools: {new_tools}")
            
            # Record evolution
            self.log["generations"].append(result)
        
        self.save_log()
        
        return results
    
    def generate_report(self):
        """Generate evolution report"""
        patterns = self.analyze_patterns()
        
        report = {
            "timestamp": datetime.now().isoformat(),
            "total_generations": len(self.log["generations"]),
            "total_created": len(self.log["created_tools"]),
            "patterns": {k: len(v) for k, v in patterns.items()},
            "suggestions": self.generate_suggestions(patterns)
        }
        
        return report
    
    def generate_suggestions(self, patterns):
        """Generate actionable suggestions based on patterns"""
        suggestions = []
        
        if patterns["optimization_points"]:
            suggestions.append(f"Optimize {len(patterns['optimization_points'])} tools (add caching)")
        if patterns["missing_features"]:
            suggestions.append(f"Add features to {len(patterns['missing_features'])} tools")
        if patterns["repeated_code"]:
            suggestions.append(f"Refactor {len(patterns['repeated_code'])} tools")
        
        if not suggestions:
            suggestions.append("System is well-optimized")
        
        return suggestions

def main():
    evolver = SelfEvolution()
    
    print("\n[AUTO-EVOLVE-001] Self-Evolution System")
    print("=" * 50)
    
    if "--evolve" in sys.argv:
        iterations = int(sys.argv[sys.argv.index("--evolve") + 1]) if "--evolve" in sys.argv and len(sys.argv) > 2 else 3
        results = evolver.evolve(iterations)
        
        print(f"\n[EVOLED] {len(results)} generations complete")
        for r in results:
            print(f"  Gen {r['generation']}: {r['new_tools']}")
    
    elif "--analyze" in sys.argv:
        patterns = evolver.analyze_patterns()
        print("\n[PATTERN ANALYSIS]")
        for k, v in patterns.items():
            print(f"  {k}: {len(v)} found")
            if v:
                for item in v[:3]:
                    print(f"    - {item}")
    
    elif "--report" in sys.argv:
        report = evolver.generate_report()
        print("\n[EVOLUTION REPORT]")
        print(f"  Generations: {report['total_generations']}")
        print(f"  Created tools: {report['total_created']}")
        print(f"\n  Suggestions:")
        for s in report['suggestions']:
            print(f"    - {s}")
    
    else:
        print("\nUsage:")
        print("  --evolve [n]    Run n evolution cycles")
        print("  --analyze       Analyze patterns")
        print("  --report        Generate report")

if __name__ == "__main__":
    main()
