import logging
logger = logging.getLogger(__name__)

#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
思维导图生成器 - 可视化头脑风暴创意结构
"""

import json
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional

class BrainstormMindMap:
    """思维导图生成器"""
    
    def __init__(self):
        self.output_dir = Path("flow-archive/20260320-brainstorm-v2/mindmaps")
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_from_ideas(self, ideas: List[Dict], title: str = "Brainstorm") -> Dict:
        """从创意生成思维导图"""
        
        # 构建思维导图结构
        mindmap = {
            "title": title,
            "created_at": datetime.now().isoformat(),
            "central_topic": title,
            "main_branches": self._organize_into_branches(ideas),
            "total_ideas": len(ideas),
            "format": "markdown"
        }
        
        # 生成 Markdown 格式思维导图
        md_content = self._to_markdown(mindmap)
        
        # 保存文件
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_file = self.output_dir / f"mindmap_{timestamp}.md"
        
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(md_content)
        
        return {
            "success": True,
            "file": str(output_file),
            "total_ideas": len(ideas),
            "branches": len(mindmap['main_branches']),
            "format": "markdown"
        }
    
    def _organize_into_branches(self, ideas: List[Dict]) -> List[Dict]:
        """将创意组织成分支"""
        
        # 按类别分组
        categories = {}
        for idea in ideas:
            category = idea.get('category', 'Uncategorized')
            if category not in categories:
                categories[category] = []
            categories[category].append(idea)
        
        # 构建分支
        branches = []
        for category, category_ideas in categories.items():
            branch = {
                "name": category,
                "subtopics": [
                    {
                        "name": idea.get('name', 'Unnamed'),
                        "details": idea.get('description', ''),
                        "impact_score": idea.get('impact_score', 5)
                    }
                    for idea in category_ideas
                ]
            }
            branches.append(branch)
        
        return branches
    
    def _to_markdown(self, mindmap: Dict) -> str:
        """转换为 Markdown 格式"""
        
        lines = []
        lines.append(f"# {mindmap['title']} - Mind Map\n")
        lines.append(f"**Created:** {mindmap['created_at']}\n")
        lines.append(f"**Total Ideas:** {mindmap['total_ideas']}\n")
        lines.append(f"**Main Branches:** {len(mindmap['main_branches'])}\n")
        lines.append("\n---\n")
        
        # 中心主题
        lines.append(f"\n## 🎯 {mindmap['central_topic']}\n")
        
        # 主分支
        for i, branch in enumerate(mindmap['main_branches'], 1):
            lines.append(f"\n### Branch {i}: {branch['name']}\n")
            
            for j, subtopic in enumerate(branch['subtopics'], 1):
                impact = "⭐" * min(5, max(1, subtopic.get('impact_score', 5) // 2))
                lines.append(f"- **{j}. {subtopic['name']}** {impact}")
                if subtopic.get('details'):
                    lines.append(f"  - {subtopic['details']}")
        
        lines.append("\n---\n")
        lines.append("\n*Generated by Brainstorm MindMap Generator*\n")
        
        return "\n".join(lines)
    
    def generate_comparison_map(self, iterations: List[Dict]) -> Dict:
        """生成迭代对比思维导图"""
        
        comparison = {
            "title": "Brainstorm Iteration Comparison",
            "created_at": datetime.now().isoformat(),
            "iterations": len(iterations),
            "comparison": []
        }
        
        for i, iteration in enumerate(iterations, 1):
            comp = {
                "iteration": i,
                "ideas_count": iteration.get('ideas_count', 0),
                "top_ideas": iteration.get('top_ideas', [])[:3],
                "critic_score": iteration.get('critic_score', 0)
            }
            comparison['comparison'].append(comp)
        
        # 生成 Markdown
        md_lines = []
        md_lines.append(f"# {comparison['title']}\n")
        md_lines.append(f"**Generated:** {comparison['created_at']}\n")
        md_lines.append(f"**Total Iterations:** {comparison['iterations']}\n")
        md_lines.append("\n---\n")
        
        for comp in comparison['comparison']:
            md_lines.append(f"\n## Iteration {comp['iteration']}\n")
            md_lines.append(f"- Ideas: {comp['ideas_count']}")
            md_lines.append(f"- Critic Score: {comp['critic_score']}")
            md_lines.append(f"- Top Ideas:")
            for idea in comp['top_ideas']:
                md_lines.append(f"  - {idea}")
        
        output_file = self.output_dir / "iteration_comparison.md"
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write("\n".join(md_lines))
        
        return {
            "success": True,
            "file": str(output_file),
            "iterations_compared": len(iterations)
        }
    
    def get_stats(self) -> Dict:
        """获取统计"""
        mindmap_files = list(self.output_dir.glob("*.md"))
        
        return {
            "total_mindmaps": len(mindmap_files),
            "latest_mindmap": max(
                [f.stat().st_mtime for f in mindmap_files],
                default=0
            )
        }
    
    def display_status(self) -> str:
        """显示状态"""
        stats = self.get_stats()
        
        output = []
        output.append("\n" + "=" * 70)
        output.append(" " * 22 + "Mind Map Generator")
        output.append("=" * 70)
        
        output.append(f"\n[Stats]")
        output.append(f"  Total Mind Maps:  {stats['total_mindmaps']}")
        
        output.append(f"\n[Output Directory]")
        output.append(f"  {self.output_dir}")
        
        output.append(f"\n[Formats Supported]")
        output.append(f"  - Markdown (primary)")
        output.append(f"  - JSON (structured data)")
        
        output.append("\n" + "=" * 70)
        
        return "\n".join(output)
    
    def run(self, ideas: List[Dict], title: str = "Brainstorm") -> Dict:
        """运行思维导图生成"""
        return self.generate_from_ideas(ideas, title)

logging.basicConfig(level=logging.INFO)
def main():
    """测试入口"""
    mindmap = BrainstormMindMap()
    
    print("Mind Map Generator Test")
    print("=" * 70)
    
    # 测试：生成思维导图
    test_ideas = [
        {"name": "Idea 1", "description": "Description 1", "category": "Performance", "impact_score": 8},
        {"name": "Idea 2", "description": "Description 2", "category": "UX", "impact_score": 7},
        {"name": "Idea 3", "description": "Description 3", "category": "Performance", "impact_score": 9},
        {"name": "Idea 4", "description": "Description 4", "category": "Security", "impact_score": 6},
    ]
    
    result = mindmap.generate_from_ideas(test_ideas, "Test Brainstorm")
    
    print(f"\n[OK] Generated mind map: {result['file']}")
    print(f"Total ideas: {result['total_ideas']}")
    print(f"Branches: {result['branches']}")
    
    # 显示状态
    print(mindmap.display_status())
    
    print(f"\n[OK] Mind map test completed")

if __name__ == "__main__":
    main()
