@echo off
REM Stock PRO Pipeline - 2026-03-22 10:28
REM Auto-generated by Stock PRO v10.0

echo.
echo ============================================================
echo Stock PRO Pipeline - NVDA META JPM
echo ============================================================
echo.

REM 1. Generate comparison report
echo [1/4] Generating comparison report...
python "%~dp0stock_pro_v4.py" --compare NVDA META JPM

REM 2. Export to CSV
echo.
echo [2/4] Exporting to CSV...
python "%~dp0stock_pro_v4.py" --csv NVDA META JPM

REM 3. Check alerts
echo.
echo [3/4] Checking price alerts...
python "%~dp0stock_pro_v4.py" --alert NVDA META JPM

REM 4. Sync to Obsidian
echo.
echo [4/4] Syncing to Obsidian...
python "%~dp0stock_pro_v4.py" --obsidian NVDA META JPM

echo.
echo ============================================================
echo Pipeline Complete!
echo ============================================================
pause
