#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Workflow Manager v3.0 - Simplified & Optimized

Features:
- 5 commands only (start/add/commit/status/check)
- 4 stages (developing/documenting/verifying/completed)
- Auto UTF-8 encoding
- Auto stage detection
- Command aliases support

Author: OpenClaw Team
Date: 2026-03-16
Version: 3.0
"""

import sys
import json
import subprocess
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional
from dataclasses import dataclass, asdict, field

# UTF-8 encoding for Windows console
try:
    sys.stdout.reconfigure(encoding='utf-8')
except AttributeError:
    import codecs
    sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer)


@dataclass
class WorkflowState:
    """Simplified workflow state"""
    iteration: int
    stage: str = 'developing'  # developing/documenting/verifying/completed
    started_at: str = field(default_factory=lambda: datetime.now().isoformat())
    files: List[str] = field(default_factory=list)
    reports: List[str] = field(default_factory=list)
    memory_updated: bool = False
    tests_passed: bool = False
    commit_count: int = 0
    completed_at: Optional[str] = None
    
    def auto_detect_stage(self) -> str:
        """Auto-detect current stage based on completed items"""
        if self.completed_at:
            return 'completed'
        elif self.memory_updated and len(self.reports) > 0:
            return 'verifying'
        elif len(self.reports) > 0:
            return 'documenting'
        else:
            return 'developing'


class WorkflowManager:
    """Simplified workflow manager - 5 commands only"""
    
    STATE_FILE = Path('data/workflow_state.json')
    
    STAGES = {
        'developing': '💻 Developing',
        'documenting': '📝 Documenting',
        'verifying': '🔍 Verifying',
        'completed': '✅ Completed'
    }
    
    def __init__(self):
        self.state: Optional[WorkflowState] = None
        self.state_file = self.STATE_FILE
        self.state_file.parent.mkdir(parents=True, exist_ok=True)
        self.load()
    
    def load(self):
        """Load state from disk"""
        if self.state_file.exists():
            with open(self.state_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
                self.state = WorkflowState(**data)
    
    def save(self):
        """Save state to disk"""
        if self.state:
            # Auto-detect stage
            self.state.stage = self.state.auto_detect_stage()
            
            with open(self.state_file, 'w', encoding='utf-8') as f:
                json.dump(asdict(self.state), f, indent=2, ensure_ascii=False)
    
    def start(self, iteration: int, auto_template: bool = True):
        """Start new iteration"""
        self.state = WorkflowState(iteration=iteration)
        self.save()
        
        print(f"\n{'='*70}")
        print(f"✅ Iteration {iteration} Started")
        print(f"{'='*70}")
        print(f"📍 Stage: {self.STAGES['developing']}")
        print(f"⏰ Started: {self.state.started_at}")
        
        if auto_template:
            self._generate_template(iteration)
        
        print(f"\n💡 Next: workflow add <file.py>")
        print(f"{'='*70}\n")
    
    def _generate_template(self, iteration: int):
        """Auto-generate iteration template"""
        template = f"""# 📋 Iteration {iteration} Plan

**Date:** {datetime.now().strftime('%Y-%m-%d')}  
**Goal:** [Describe goal]

## ✅ Checklist

### Development
- [ ] Create tools
- [ ] Write tests
- [ ] Pass tests

### Documentation
- [ ] Create report
- [ ] Update MEMORY.md

### Verification
- [ ] Run: workflow check
- [ ] Score = 100

### Commit
- [ ] Run: workflow commit "Title"
- [ ] Verify 1 commit
- [ ] Push

## 📊 Files

### Tools
- [ ] 

### Reports
- [ ] ITERATION-{iteration}-REPORT.md

---
_Generated by Workflow Manager v3.0_
"""
        template_file = Path(f'ITERATION-{iteration}-PLAN.md')
        template_file.write_text(template, encoding='utf-8')
        print(f"✅ Template: ITERATION-{iteration}-PLAN.md")
    
    def add(self, files: List[str], report: bool = False):
        """Add files or reports"""
        if not self.state:
            print("❌ No active iteration")
            print("💡 Run: workflow start <iteration>")
            return
        
        if report:
            for f in files:
                if f not in self.state.reports:
                    self.state.reports.append(f)
            print(f"✅ Added reports: {', '.join(files)}")
        else:
            for f in files:
                if f not in self.state.files:
                    self.state.files.append(f)
            print(f"✅ Added files: {', '.join(files)}")
        
        self.save()
        self._show_progress()
    
    def tests(self, passed: bool = True):
        """Mark tests as passed"""
        if not self.state:
            print("❌ No active iteration")
            return
        
        self.state.tests_passed = passed
        self.save()
        print(f"✅ Tests: {'Passed' if passed else 'Failed'}")
        self._show_progress()
    
    def memory(self, updated: bool = True):
        """Mark MEMORY.md as updated"""
        if not self.state:
            print("❌ No active iteration")
            return
        
        self.state.memory_updated = updated
        self.save()
        print(f"✅ MEMORY.md: {'Updated' if updated else 'Not updated'}")
        self._show_progress()
    
    def check(self) -> Dict:
        """Check workflow readiness"""
        if not self.state:
            return {'error': 'No active iteration'}
        
        # Auto-detect stage
        self.state.stage = self.state.auto_detect_stage()
        
        checks = {
            'has_files': len(self.state.files) > 0,
            'has_reports': len(self.state.reports) > 0,
            'memory_updated': self.state.memory_updated,
            'tests_passed': self.state.tests_passed,
            'single_commit': self.state.commit_count == 0,
        }
        
        checks['ready'] = all([
            checks['has_files'],
            checks['has_reports'],
            checks['memory_updated'],
            checks['tests_passed']
        ])
        
        checks['score'] = sum(checks.values()) / (len(checks) - 1) * 100  # Exclude 'ready'
        
        return checks
    
    def status(self):
        """Show workflow status"""
        if not self.state:
            print("\n❌ No active iteration")
            print("💡 Start: workflow start <iteration>\n")
            return
        
        checks = self.check()
        
        print(f"\n{'='*70}")
        print(f"📊 Iteration {self.state.iteration} Status")
        print(f"{'='*70}\n")
        
        # Stage progress bar
        stages = ['developing', 'documenting', 'verifying', 'completed']
        current_idx = stages.index(self.state.stage) if self.state.stage in stages else 0
        
        progress = ""
        for i, stage in enumerate(stages):
            if i <= current_idx:
                progress += f"● {self.STAGES[stage].split()[1]} "
            else:
                progress += f"○ {self.STAGES[stage].split()[1]} "
        
        print(f"📍 Stage: {progress}")
        print(f"⏰ Started: {self.state.started_at}")
        if self.state.completed_at:
            print(f"⏰ Completed: {self.state.completed_at}")
        
        print(f"\n📁 Files ({len(self.state.files)}):")
        for f in self.state.files:
            print(f"  ✅ {f}")
        
        print(f"\n📄 Reports ({len(self.state.reports)}):")
        for r in self.state.reports:
            print(f"  ✅ {r}")
        
        print(f"\n✅ Checks:")
        print(f"  Files: {'✅' if checks['has_files'] else '❌'}")
        print(f"  Reports: {'✅' if checks['has_reports'] else '❌'}")
        print(f"  MEMORY.md: {'✅' if checks['memory_updated'] else '❌'}")
        print(f"  Tests: {'✅' if checks['tests_passed'] else '❌'}")
        
        score = checks.get('score', 0)
        bar_len = int(score / 5)
        bar = "█" * bar_len + "░" * (20 - bar_len)
        print(f"\n📊 Score: {score:.0f}/100")
        print(f"   [{bar}]")
        
        if checks['ready']:
            print(f"\n🎯 Ready to commit: ✅ YES")
            print(f"💡 Next: workflow commit \"Title\"")
        else:
            print(f"\n⚠️  Not ready yet")
            missing = []
            if not checks['has_files']:
                missing.append("files")
            if not checks['has_reports']:
                missing.append("reports")
            if not checks['memory_updated']:
                missing.append("MEMORY.md update")
            if not checks['tests_passed']:
                missing.append("tests")
            print(f"   Missing: {', '.join(missing)}")
        
        print(f"\n{'='*70}\n")
    
    def commit(self, title: str, features: List[str], lessons: List[str]):
        """Automated single commit"""
        if not self.state:
            print("❌ No active iteration")
            return 1
        
        checks = self.check()
        if not checks['ready']:
            print("❌ Not ready to commit!")
            print(f"   Score: {checks.get('score', 0):.0f}/100")
            print("💡 Run: workflow check")
            return 1
        
        print(f"\n{'='*70}")
        print(f"🎯 Committing Iteration {self.state.iteration}")
        print(f"{'='*70}\n")
        
        # Get changed files
        result = subprocess.run(
            ['git', 'status', '--porcelain'],
            capture_output=True, text=True, timeout=10, encoding='utf-8'
        )
        changed = [line.split()[1] for line in result.stdout.split('\n') if line.strip()]
        
        if not changed:
            print("⚠️  No changes to commit")
            return 0
        
        print(f"📦 Files: {len(changed)}")
        for f in changed[:10]:
            print(f"   {f}")
        if len(changed) > 10:
            print(f"   ... and {len(changed) - 10} more")
        
        # Add all
        subprocess.run(['git', 'add', '-A'], check=True, timeout=10)
        
        # Create commit message
        date = datetime.now().strftime('%Y-%m-%d')
        msg = f"""⚡ Obsidian Skills Iteration {self.state.iteration}: {title}

New Features ({len(features)}):
{chr(10).join(f'- ✅ {f}' for f in features)}

New Lessons ({len(lessons)}):
{chr(10).join(f'- [{l}]' for l in lessons)}

Performance:
- Git commits: 1 (single commit)
- Process: code + memory + report → single commit

Date: {date}
Iteration: {self.state.iteration}

Workflow:
- Files: {len(self.state.files)}
- Reports: {len(self.state.reports)}
- Score: {checks.get('score', 0):.0f}/100
"""
        
        # Commit
        subprocess.run(['git', 'commit', '-m', msg], check=True, timeout=30)
        
        # Get hash
        result = subprocess.run(
            ['git', 'log', '-1', '--format=%H'],
            capture_output=True, text=True, timeout=10, encoding='utf-8'
        )
        commit_hash = result.stdout.strip()[:7]
        
        # Push
        print("\n🚀 Pushing...")
        subprocess.run(['git', 'push'], check=True, timeout=30)
        
        # Update state
        self.state.commit_count = 1
        self.state.completed_at = datetime.now().isoformat()
        self.state.stage = 'completed'
        self.save()
        
        print(f"\n{'='*70}")
        print(f"✅ Iteration {self.state.iteration} Complete!")
        print(f"📍 Commit: {commit_hash}")
        print(f"📊 Score: {checks.get('score', 0):.0f}/100")
        print(f"{'='*70}\n")
        
        return 0
    
    def _show_progress(self):
        """Show quick progress"""
        stage = self.state.auto_detect_stage()
        print(f"📍 Stage: {self.STAGES.get(stage, stage)}")
        print(f"   Files: {len(self.state.files)}, Reports: {len(self.state.reports)}")


def main():
    import argparse
    
    parser = argparse.ArgumentParser(
        description='Workflow Manager v3.0',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Commands:
  start <iteration>     Start new iteration
  add <files>           Add files
  add-report <files>    Add reports
  tests                 Mark tests passed
  memory                Mark MEMORY.md updated
  check                 Check readiness
  status                Show status
  commit "<title>"      Commit iteration

Examples:
  workflow start 10
  workflow add tool.py
  workflow tests
  workflow memory
  workflow add-report REPORT.md
  workflow check
  workflow commit "Feature Complete"
        """
    )
    
    subparsers = parser.add_subparsers(dest='cmd', help='Command')
    
    # Start
    p_start = subparsers.add_parser('start', help='Start iteration')
    p_start.add_argument('iteration', type=int, help='Iteration number')
    p_start.add_argument('--no-template', action='store_true', help='Skip template')
    
    # Add
    p_add = subparsers.add_parser('add', help='Add files')
    p_add.add_argument('files', nargs='+', help='Files to add')
    
    # Add report
    p_addr = subparsers.add_parser('add-report', help='Add reports')
    p_addr.add_argument('files', nargs='+', help='Report files')
    
    # Tests
    p_tests = subparsers.add_parser('tests', help='Mark tests passed')
    
    # Memory
    p_mem = subparsers.add_parser('memory', help='Mark MEMORY.md updated')
    
    # Check
    p_check = subparsers.add_parser('check', help='Check readiness')
    
    # Status
    p_status = subparsers.add_parser('status', help='Show status')
    
    # Commit
    p_commit = subparsers.add_parser('commit', help='Commit iteration')
    p_commit.add_argument('title', type=str, help='Commit title')
    p_commit.add_argument('--feature', action='append', help='Feature (repeat)')
    p_commit.add_argument('--lesson', action='append', help='Lesson (repeat)')
    
    args = parser.parse_args()
    
    wm = WorkflowManager()
    
    if args.cmd == 'start':
        wm.start(args.iteration, not args.no_template)
    elif args.cmd == 'add':
        wm.add(args.files)
    elif args.cmd == 'add-report':
        wm.add(args.files, report=True)
    elif args.cmd == 'tests':
        wm.tests()
    elif args.cmd == 'memory':
        wm.memory()
    elif args.cmd == 'check':
        checks = wm.check()
        print(json.dumps(checks, indent=2, ensure_ascii=False))
    elif args.cmd == 'status':
        wm.status()
    elif args.cmd == 'commit':
        features = args.feature or []
        lessons = args.lesson or []
        sys.exit(wm.commit(args.title, features, lessons))
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
