// Auto-generated by scripts/generate-tests.mjs
import { describe, it, expect } from 'vitest';

describe('src/stores/arenaStore.js', () => {
  describe('arenaStore', () => {
    it('should be exported', () => {
      expect(arenaStore).toBeDefined();
    });
  });
});
