// Auto-generated by scripts/generate-tests.mjs
import { describe, it, expect } from 'vitest';

describe('src/stores/gameStore.js', () => {
  describe('gameStore', () => {
    it('should be exported', () => {
      expect(gameStore).toBeDefined();
    });
  });
  describe('selectedAgent', () => {
    it('should be exported', () => {
      expect(selectedAgent).toBeDefined();
    });
  });
  describe('agentPower', () => {
    it('should be exported', () => {
      expect(agentPower).toBeDefined();
    });
  });
  describe('winRate', () => {
    it('should be exported', () => {
      expect(winRate).toBeDefined();
    });
  });
});
