# arXiv Stream Collector - Grab->Analyze->Store, no backlog
# POET-X Optimization #1: Input-centric reformulation

param([string]$Date = (Get-Date -Format "yyyy-MM-dd"))

Write-Host "arXiv Stream Collect: $Date" -ForegroundColor Cyan

$OutputDir = "D:\OpenClaw\workspace\41-medium\archive\$Date"
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
}

$categories = @("cs.AI", "cs.LG", "cs.CL")
$processedCount = 0
$skippedCount = 0

foreach ($cat in $categories) {
    Write-Host "[$cat] Fetching..." -ForegroundColor Yellow
    
    $url = "http://export.arxiv.org/api/query?search_query=cat:$cat&start=0&max_results=3&sortBy=submittedDate&sortOrder=descending"
    
    try {
        $response = Invoke-WebRequest -Uri $url -TimeoutSec 30 -UseBasicParsing
        $xml = [xml]$response.Content
        
        foreach ($entry in $xml.feed.entry) {
            $title = $entry.title -replace "`n", " "
            $id = $entry.id
            $arxivId = $id -replace "http://arxiv.org/abs/", ""
            
            # Check if exists
            $existingFile = Get-ChildItem -Path $OutputDir -Filter "*$arxivId*.md" -ErrorAction SilentlyContinue
            if ($existingFile) {
                Write-Host "  [Skip] $title" -ForegroundColor Gray
                $skippedCount++
                continue
            }
            
            # Direct output (stream processing)
            $notePath = Join-Path $OutputDir "$(Get-Date -Format 'yyyyMMdd-HHmmss')-$arxivId.md"
            $noteContent = @"
---
title: $title
source: arXiv
id: $id
category: $cat
published: $($entry.published)
collected: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
priority: medium
status: collected
---

## Core Question
TBD.

## Core Thesis
TBD.

## One-Sentence Essence
TBD.

---
*Auto-generated by arXiv Stream Collector*
"@
            $noteContent | Out-File -FilePath $notePath -Encoding utf8
            Write-Host "  [OK] $title" -ForegroundColor Green
            $processedCount++
        }
    } catch {
        Write-Host "  [Error] $_" -ForegroundColor Red
    }
}

Write-Host "Done: $processedCount papers, Skipped: $skippedCount" -ForegroundColor Green
