// ~/.omc/patrol-agent/src/planWriter.js
// Write new plans to docs/superpowers/plans/ from research ideas

import { writeFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { createHash } from 'crypto';

const PLANS_DIR = 'D:/OpenClaw/workspace/docs/superpowers/plans';

/**
 * Compute a simple hash for deduplication.
 * @param {string} input
 * @returns {string}
 */
function computeHash(input) {
  return createHash('sha256').update(input).digest('hex').slice(0, 16);
}

/**
 * Write a new plan file from a research idea.
 * @param {{ title: string, url: string, summary: string, confidence: number, source: string, generated_at: string }} idea
 * @returns {{ success: boolean, planId: string, file: string }}
 */
export function writePlanFromResearch(idea) {
  try {
    if (!existsSync(PLANS_DIR)) {
      mkdirSync(PLANS_DIR, { recursive: true });
    }

    const id = idea.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60);

    const hash = computeHash(idea.title + idea.url);
    const timestamp = new Date().toISOString().slice(0, 10);
    const filename = `${timestamp}-${id}.md`;
    const filePath = join(PLANS_DIR, filename);

    const content = `---
status: pending
id: ${id}
hash: sha256:${hash}
generated_from: research
source_url: ${idea.url}
confidence: ${idea.confidence.toFixed(2)}
created_at: ${idea.generated_at}
updated_at: ${idea.generated_at}
---

# Plan: ${idea.title}

**Research source**: ${idea.url}

**研究摘要**: ${idea.summary}

**置信度**: ${idea.confidence.toFixed(2)}

**为什么适合 workspace**: 来自 ${idea.source} 的高质量研究，与现有项目相关。

**实施建议**: 待补充。

*Generated by patrol agent on ${new Date().toISOString()}*
`;

    writeFileSync(filePath, content, 'utf-8');
    return { success: true, planId: id, file: filePath };
  } catch (err) {
    return { success: false, planId: '', file: '', error: err.message };
  }
}
