#!/usr/bin/env python3
"""
LIG Risk Monitor - LIG 风险预警系统
Function: Monitor LIG field technology competition
Created: 2026-03-13 (Critic v5.0 fix)
Usage: python lig-risk-monitor.py
Schedule: Daily 7AM auto-run
"""

import json
import requests
from datetime import datetime
from pathlib import Path

# Config
WORKSPACE = Path("D:/OpenClaw/workspace")
OUTPUT_DIR = WORKSPACE / "21-reports/lig-risk"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Thresholds
THRESHOLDS = {
    "pubmed_papers_per_week": 10,
    "patent_applications_per_month": 5,
    "major_company_activity": 3,
}

def fetch_pubmed_lig_papers():
    """Fetch PubMed LIG papers"""
    base_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
    params = {
        "db": "pubmed",
        "term": "laser-induced graphene OR LIG graphene",
        "retmax": 100,
        "retmode": "json"
    }

    try:
        response = requests.get(base_url, params=params, timeout=30)
        data = response.json()
        paper_ids = data.get("esearchresult", {}).get("idlist", [])
        return len(paper_ids)
    except Exception as e:
        print(f"PubMed query failed: {e}")
        return 0

def check_risk_level(papers_count):
    """Assess risk level"""
    if papers_count >= THRESHOLDS["pubmed_papers_per_week"] * 2:
        return "HIGH", "LIG research activity异常 high, possible tech breakthrough"
    elif papers_count >= THRESHOLDS["pubmed_papers_per_week"]:
        return "MEDIUM", "LIG research active, keep monitoring"
    else:
        return "LOW", "LIG research activity normal"

def generate_report(papers_count, risk_level, risk_message):
    """Generate risk report"""
    report = f"""# LIG Risk Monitor Report

**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}  
**Period:** Weekly (past 7 days)

---

## Risk Assessment

**Risk Level:** {risk_level}

{risk_message}

---

## Metrics

| Metric | Value | Threshold | Status |
|--------|-------|-----------|--------|
| PubMed Papers/Week | {papers_count} | {THRESHOLDS['pubmed_papers_per_week']} | {'WARNING' if papers_count >= THRESHOLDS['pubmed_papers_per_week'] else 'OK'} |
| Patent Applications | N/A | {THRESHOLDS['patent_applications_per_month']} | Pending |
| Major Company Activity | N/A | {THRESHOLDS['major_company_activity']} | Pending |

---

## Analysis

### PubMed Trend
- Papers this week: {papers_count}
- Threshold: {THRESHOLDS['pubmed_papers_per_week']} papers/week
- Status: {'EXCEEDS' if papers_count >= THRESHOLDS['pubmed_papers_per_week'] else 'NORMAL'}

---

## Recommendations

{'''1. **Enhance Monitoring** - Paper count exceeds threshold
2. **Competitive Analysis** - Analyze high-citation papers
3. **Patent Tracking** - Monitor core patent applications''' if papers_count >= THRESHOLDS['pubmed_papers_per_week'] else '''1. **Regular Monitoring** - Activity level normal
2. **Continue Tracking** - Maintain weekly frequency
3. **Opportunity ID** - Watch emerging research directions'''}

---

## Next Report

**Scheduled:** {datetime.now().strftime('%Y-%m-%d')} 07:00 AM

---

*Generated by LIG Risk Monitor v1.0*  
*Last Updated:* {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""
    return report

def main():
    print("=" * 50)
    print("LIG Risk Monitor")
    print("=" * 50)
    print()

    # 1. Fetch PubMed data
    print("[1/3] Fetching PubMed data...")
    papers_count = fetch_pubmed_lig_papers()
    print(f"  + PubMed papers: {papers_count}")

    # 2. Assess risk
    print()
    print("[2/3] Assessing risk level...")
    risk_level, risk_message = check_risk_level(papers_count)
    print(f"  + Risk Level: {risk_level}")
    print(f"  + Message: {risk_message}")

    # 3. Generate report
    print()
    print("[3/3] Generating report...")
    report = generate_report(papers_count, risk_level, risk_message)

    output_file = OUTPUT_DIR / f"lig-risk-report-{datetime.now().strftime('%Y%m%d')}.md"
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(report)

    print(f"  + Report saved: {output_file}")

    print()
    print("=" * 50)
    print("LIG Risk Monitor Complete!")
    print("=" * 50)

if __name__ == '__main__':
    main()
