#!/usr/bin/env pwsh
# Check broken links in Markdown files
# Usage: .\check-broken-links.ps1 [-Path <dir>] [-Verbose]

param(
    [string]$Path = "D:\OpenClaw\workspace",
    [switch]$Verbose,
    [string]$OutputFile = "broken-links-report.md"
)

$ErrorActionPreference = "Continue"
$stats = @{Checked = 0; Broken = 0; Skipped = 0}
$brokenLinks = @()
$totalLinks = 0

Write-Host "Checking broken links..." -ForegroundColor Cyan
Write-Host "Path: $Path"
Write-Host "Time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Write-Host ""

$mdFiles = Get-ChildItem -Path $Path -Filter "*.md" -Recurse -Exclude $OutputFile
$totalFiles = $mdFiles.Count
Write-Host "Found $totalFiles Markdown files"
Write-Host ""

$linkPattern = '\[\[([^\]|]+)(?:\|[^\]]+)?\]\]'
$excludeDirs = @('.git', 'node_modules', '__pycache__', '.venv', 'Archive', '05-templates')

foreach ($file in $mdFiles) {
    $skip = $false
    foreach ($ex in $excludeDirs) {
        if ($file.FullName -like "*\$ex\*") { $skip = $true; $stats.Skipped++; break }
    }
    if ($skip) { continue }
    
    $stats.Checked++
    $content = Get-Content $file.FullName -Raw -ErrorAction SilentlyContinue
    if (-not $content) { continue }
    
    $links = [regex]::Matches($content, $linkPattern)
    
    foreach ($link in $links) {
        $totalLinks++
        $linkText = $link.Groups[1].Value.Trim()
        
        if ($linkText -match '^(http|https|mailto:|#)') { continue }
        
        $targetPath = $linkText -replace '^\.+/',''
        $possibleExtensions = @('.md', '')
        $found = $false
        
        foreach ($ext in $possibleExtensions) {
            $testPath = Join-Path $file.DirectoryName $("$targetPath$ext")
            if (Test-Path -LiteralPath $testPath -PathType Leaf -ErrorAction SilentlyContinue) { $found = $true; break }
            
            $testPath2 = Join-Path $Path $("$targetPath$ext")
            if (Test-Path -LiteralPath $testPath2 -PathType Leaf -ErrorAction SilentlyContinue) { $found = $true; break }
            
            $testPath3 = Join-Path $file.DirectoryName "$targetPath/README.md"
            if (Test-Path -LiteralPath $testPath3 -PathType Leaf -ErrorAction SilentlyContinue) { $found = $true; break }
        }
        
        if (-not $found) {
            # Skip placeholder links (templates, examples)
            if ($linkText -match '^(xxx|论文 | 概念 | 趋势 | 笔记 | 标题 | 名称|OK|)$') { continue }
            if ($linkText -match '^\d+\.\d+') { continue }  # Skip numbers like "10.0, 50.0"
            
            $lineNum = 0
            try {
                $lines = Get-Content $file.FullName
                for ($i = 0; $i -lt $lines.Length; $i++) {
                    if ($lines[$i] -match [regex]::Escape($linkText)) {
                        $lineNum = $i + 1
                        break
                    }
                }
            } catch {}
            
            $brokenLinks += [PSCustomObject]@{
                File = $file.FullName.Replace($Path, '').TrimStart('\')
                Link = $linkText
                Line = $lineNum
            }
            $stats.Broken++
            
            if ($Verbose) {
                Write-Host "  X $($file.Name): $linkText" -ForegroundColor Yellow
            }
        }
    }
    
    if ($stats.Checked % 50 -eq 0) {
        Write-Progress -Activity "Checking links" -Status "$($stats.Checked)/$totalFiles" -PercentComplete (($stats.Checked / $totalFiles) * 100)
    }
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Results" -ForegroundColor Cyan
Write-Host "========================================"
Write-Host "Files checked: $($stats.Checked)"
Write-Host "Files skipped: $($stats.Skipped)"
Write-Host "Total links: $totalLinks"
Write-Host "Broken links: $($stats.Broken)" -ForegroundColor $(if ($stats.Broken -eq 0) { 'Green' } else { 'Red' })
Write-Host "Broken rate: $([math]::Round($stats.Broken / $totalLinks * 100, 2))%"
Write-Host ""

if ($brokenLinks.Count -gt 0) {
    $report = @"
# Broken Links Report

**Generated:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')  
**Path:** $Path  
**Files checked:** $($stats.Checked)  
**Total links:** $totalLinks  
**Broken links:** $($stats.Broken)  
**Broken rate:** $([math]::Round($stats.Broken / $totalLinks * 100, 2))%

---

## Broken Links

| File | Link | Line |
|------|------|------|
"@
    
    foreach ($broken in $brokenLinks | Group-Object File) {
        foreach ($item in $broken.Group) {
            $report += "| $($item.File) | ``$($item.Link)`` | $($item.Line) |`n"
        }
    }
    
    $report += "`n---`n*Auto-generated by check-broken-links.ps1*"
    
    $reportPath = Join-Path $Path $OutputFile
    $report | Out-File -FilePath $reportPath -Encoding utf8
    Write-Host "Report saved: $reportPath" -ForegroundColor Green
} else {
    Write-Host "No broken links found!" -ForegroundColor Green
}

Write-Host ""
Write-Host "Done!" -ForegroundColor Cyan
