// scripts/generate-tests.mjs — Auto-generate vitest test stubs for agent-arena
// Run: node scripts/generate-tests.mjs
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'fs';
import { join, dirname, relative, posix } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SRC = join(ROOT, 'src');

function toPosix(p) {
  return p.replace(/\\/g, '/');
}

function extractExports(content) {
  const exports = [];
  const fnRegex = /export\s+(?:async\s+)?function\s+(\w+)\s*\(([^)]*)\)/g;
  let m;
  while ((m = fnRegex.exec(content)) !== null) {
    exports.push({ type: 'function', name: m[1], params: m[2].trim() });
  }
  const constRegex = /export\s+const\s+(\w+)\s*=/g;
  while ((m = constRegex.exec(content)) !== null) {
    exports.push({ type: 'const', name: m[1] });
  }
  return exports;
}

function generateTestFile(relPath, exports) {
  const testRel = relPath.replace(/\.js$/, '.test.js');
  let content = '// Auto-generated by scripts/generate-tests.mjs\n';
  content += "import { describe, it, expect } from 'vitest';\n\n";
  content += "describe('" + relPath + "', () => {\n";
  for (const exp of exports) {
    if (exp.type === 'function') {
      content += "  describe('" + exp.name + "', () => {\n";
      content += "    it('should be a function', () => {\n";
      content += "      expect(typeof " + exp.name + ").toBe('function');\n";
      content += "    });\n";
      content += "  });\n";
    } else {
      content += "  describe('" + exp.name + "', () => {\n";
      content += "    it('should be exported', () => {\n";
      content += "      expect(" + exp.name + ").toBeDefined();\n";
      content += "    });\n";
      content += "  });\n";
    }
  }
  content += "});\n";
  return { testRel, content };
}

function walkDir(dir) {
  const files = [];
  const entries = readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkDir(full));
    } else if (entry.isFile() && entry.name.endsWith('.js') && !entry.name.endsWith('.test.js')) {
      files.push(full);
    }
  }
  return files;
}

const srcFiles = walkDir(SRC);
let generated = 0;

for (const file of srcFiles) {
  const rel = toPosix(relative(ROOT, file));
  const content = readFileSync(file, 'utf8');
  const exports = extractExports(content);
  if (!exports.length) continue;

  const { testRel, content: testContent } = generateTestFile(rel, exports);
  const outPath = join(ROOT, testRel);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, testContent, 'utf8');
  console.log('  gen ' + rel + ' -> ' + testRel);
  generated++;
}

console.log('\nGenerated ' + generated + ' test files');
